services:
  cli-proxy-api:
    image: ${CLI_PROXY_IMAGE:-eceasy/cli-proxy-api:latest}
    pull_policy: ${CLI_PROXY_PULL_POLICY:-always}
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: -port 8098
    network_mode: host
    volumes:
      - ./data:/data
    restart: unless-stopped
